{% set name = "biorange" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: file:///home/liuyan/projects/package/biorange/dist/biorange-1.4.2.tar.gz
  sha256: 00802e33eb4d8b41fe387d048c917f688db8b2293834b0ecfc1d58914a5309f9

build:
  rpaths:
      - lib/
      - lib64/
  entry_points:
    - smina = biorange.dock.smina:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0


requirements:
  host:
    - python
    - poetry-core
    - pip
  run:
    - anaconda::pandas
    - conda-forge::python >=3.10.0,<4.0.0
    - conda-forge::pyyaml
    - conda-forge::requests
    - conda-forge::mygene
    - conda-forge::networkx
    - conda-forge::matplotlib-base
    - conda-forge::matplotlib-venn
    - conda-forge::docker-py
    - conda-forge::py3dmol
    - conda-forge::gseapy >=1.1.3,<2.0.0
    - conda-forge::plotnine
    - conda-forge::bioblend
    - conda-forge::planemo
    - conda-forge::prolif
    - conda-forge::numpy 1.26.4
    - conda-forge::beautifulsoup4
    - conda-forge::termcolor
    - conda-forge::rdkit
    - conda-forge::openbabel
    - conda-forge::openmm
    - conda-forge::pdbfixer
    - conda-forge::libstdcxx-ng
    - pyfiglet
    - pytest-playwright
    - playwright-python 1.46.0

about:
  summary: ''
  license: ''
  license_file: 

extra:
  recipe-maintainers:
    - liuyan